K=10;
Gf = tf([2066],[1 136.4 2066]);
Gmfs = tf([K*2066],[1 136.4 (K+1)*2066]);
T = 0.0018;
Gmfz = c2d(Gmfs,T);
Gz = c2d(Gf,T);
step(Gmfs,Gmfz);
title('Resposta do controlador por alocacao de Polos');
tau = 0.01;
k=1;
q = exp(-T/tau);
z = zpk('z',T);
Tdh = ((1-q)*z^-k)/(1-q*z^-1 -(1-q)*z^-k);
Ddh = (1/Gmfz) *(Tdh);
Gdh = feedback(Ddh*Gmfz,1);
figure;
step(Ddh);
title('Sinal de controle do controlador Dahlin para uma entrada em degrau');
figure;
step(Gmfz,Gdh,Gf);
legend('controlador de ganho 10','Resposta controlador dahlin','Planta');